<?php

return
    [
        'default_tables' => [
            'stat_kategoris' => [
                1 => [
                    'nama' => 'Statistik Penduduk',
                ],
                2 => [
                    'nama' => 'Statistik Keluarga',
                ],
            ],
            'stats' => [
                1 => [
                    'stat_kategori_id' => 1,
                    'key' => 'agama',
                    'nama' => 'Agama',
                    'slug' => 'agama',
                    'deskripsi' => 'Jumlah Penduduk Menurut Agama',
                    'tampil' => true,
                ],
                2 => [
                    'stat_kategori_id' => 1,
                    'key' => 'pekerjaan',
                    'nama' => 'Pekerjaan',
                    'slug' => 'pekerjaan',
                    'deskripsi' => 'Jumlah Penduduk Menurut Pekerjaan',
                    'tampil' => true,
                ],
                3 => [
                    'stat_kategori_id' => 1,
                    'key' =>  'pendidikan',
                    'nama' => 'Pendidikan',
                    'slug' => 'pendidikan',
                    'deskripsi' => 'Jumlah Penduduk Menurut Pendidikan',
                    'tampil' => true,
                ],
                4 => [
                    'stat_kategori_id' => 1,
                    'key' => 'status_perkawinan',
                    'nama' => 'Status Perkawinan',
                    'slug' => 'status-perkawinan',
                    'deskripsi' => 'Jumlah Penduduk Menurut Status Perkawinan',
                    'tampil' => true,
                ],
                5 => [
                    'stat_kategori_id' => 1,
                    'key' => 'status_hubungan',
                    'nama' => 'Status Hubungan Keluarga',
                    'slug' => 'status-hubungan-keluarga',
                    'deskripsi' => 'Jumlah Penduduk Menurut Status Hubungan Keluarga',
                    'tampil' => true,
                ],
                6 => [
                    'stat_kategori_id' => 1,
                    'key' => 'kewarganegaraan',
                    'nama' => 'Kewarganegaraan',
                    'slug' => 'kewarganegaraan',
                    'deskripsi' => 'Jumlah Penduduk Menurut Kewarganegaraan',
                    'tampil' => true,
                ],
            ],
        ],
        'permission_data_operator' => [
            "view_kependudukan::bantuan",
            "view_any_kependudukan::bantuan",
            "create_kependudukan::bantuan",
            "update_kependudukan::bantuan",
            "restore_kependudukan::bantuan",
            "restore_any_kependudukan::bantuan",
            "replicate_kependudukan::bantuan",
            "reorder_kependudukan::bantuan",
            "delete_kependudukan::bantuan",
            "delete_any_kependudukan::bantuan",
            "force_delete_kependudukan::bantuan",
            "force_delete_any_kependudukan::bantuan",
            "view_kependudukan::dinamika",
            "view_any_kependudukan::dinamika",
            "create_kependudukan::dinamika",
            "update_kependudukan::dinamika",
            "restore_kependudukan::dinamika",
            "restore_any_kependudukan::dinamika",
            "replicate_kependudukan::dinamika",
            "reorder_kependudukan::dinamika",
            "delete_kependudukan::dinamika",
            "delete_any_kependudukan::dinamika",
            "force_delete_kependudukan::dinamika",
            "force_delete_any_kependudukan::dinamika",
            "view_kependudukan::kartu::keluarga",
            "view_any_kependudukan::kartu::keluarga",
            "create_kependudukan::kartu::keluarga",
            "update_kependudukan::kartu::keluarga",
            "restore_kependudukan::kartu::keluarga",
            "restore_any_kependudukan::kartu::keluarga",
            "replicate_kependudukan::kartu::keluarga",
            "reorder_kependudukan::kartu::keluarga",
            "delete_kependudukan::kartu::keluarga",
            "delete_any_kependudukan::kartu::keluarga",
            "force_delete_kependudukan::kartu::keluarga",
            "force_delete_any_kependudukan::kartu::keluarga",
            "view_kependudukan::penduduk",
            "view_any_kependudukan::penduduk",
            "create_kependudukan::penduduk",
            "update_kependudukan::penduduk",
            "restore_kependudukan::penduduk",
            "restore_any_kependudukan::penduduk",
            "replicate_kependudukan::penduduk",
            "reorder_kependudukan::penduduk",
            "delete_kependudukan::penduduk",
            "delete_any_kependudukan::penduduk",
            "force_delete_kependudukan::penduduk",
            "force_delete_any_kependudukan::penduduk",
            "view_kesehatan::anak",
            "view_any_kesehatan::anak",
            "create_kesehatan::anak",
            "update_kesehatan::anak",
            "restore_kesehatan::anak",
            "restore_any_kesehatan::anak",
            "replicate_kesehatan::anak",
            "reorder_kesehatan::anak",
            "delete_kesehatan::anak",
            "delete_any_kesehatan::anak",
            "force_delete_kesehatan::anak",
            "force_delete_any_kesehatan::anak",
            "page_DeskelProfile",
            "page_HalamanKesehatan",
            "page_PendudukAgama",
            "page_PendudukKategoriUmur",
            "page_PendudukPekerjaan",
            "page_PendudukPendidikan",
            "page_PendudukPerkawinan",
            "page_PendudukRentangUmur",
            "page_PendudukUmur",
            "page_HalamanStatistik",
            "page_WilayahAdministratif",
            "page_HalamanWilayah",
            "page_MyProfilePage",
            "widget_AgamaChart",
            "widget_KategoriUmurChart",
            "widget_PekerjaanChart",
            "widget_PendidikanChart",
            "widget_PerkawinanChart",
            "widget_RentangUmurChart",
            "widget_UmurChart",
            "widget_StatsOverview",
            "widget_DinamikaTable",
            "widget_AgamaTable",
            "widget_KategoriUmurTable",
            "widget_PekerjaanTable",
            "widget_PendidikanTable",
            "widget_PerkawinanTable",
            "widget_RentangUmurTable",
            "widget_UmurTable"
        ],

        'permission_data_monitor' => [
            "view_kependudukan::bantuan",
            "view_any_kependudukan::bantuan",
            "view_kependudukan::dinamika",
            "view_any_kependudukan::dinamika",
            "view_kependudukan::kartu::keluarga",
            "view_any_kependudukan::kartu::keluarga",
            "view_kependudukan::penduduk",
            "view_any_kependudukan::penduduk",
            "view_kesehatan::anak",
            "view_any_kesehatan::anak",
            "page_DeskelProfile",
            "page_HalamanKesehatan",
            "page_PendudukAgama",
            "page_PendudukKategoriUmur",
            "page_PendudukPekerjaan",
            "page_PendudukPendidikan",
            "page_PendudukPerkawinan",
            "page_PendudukRentangUmur",
            "page_PendudukUmur",
            "page_HalamanStatistik",
            "page_WilayahAdministratif",
            "page_HalamanWilayah",
            "page_MyProfilePage",
            "widget_AgamaChart",
            "widget_KategoriUmurChart",
            "widget_PekerjaanChart",
            "widget_PendidikanChart",
            "widget_PerkawinanChart",
            "widget_RentangUmurChart",
            "widget_UmurChart",
            "widget_StatsOverview",
            "widget_DinamikaTable",
            "widget_AgamaTable",
            "widget_KategoriUmurTable",
            "widget_PekerjaanTable",
            "widget_PendidikanTable",
            "widget_PerkawinanTable",
            "widget_RentangUmurTable",
            "widget_UmurTable"
        ]
    ];
