<?php

namespace App\Enum\Penduduk;

use Filament\Support\Contracts\HasLabel;
use Filament\Support\Contracts\HasColor;
use Filament\Support\Contracts\HasIcon;

enum EtnisSuku: string
{

        //referensi https://id.wikipedia.org/wiki/Daftar_suku_bangsa_di_Indonesia_menurut_jumlah_penduduk

    case JAWA = "Jawa";
    case SUNDA = "Sunda";
    case MELAYU = "Melayu";
    case BATAK = "Batak";
    case MADURA = "Madura";
    case BETAWI = "Betawi";
    case MINANGKABAU = "Minangkabau";
    case BUGIS = "Bugis";
    case BANTEN = "Banten";
    case BANJAR = "Banjar";
    case BALI = "Bali";
    case ACEH = "Aceh";
    case DAYAK = "Dayak";
    case SASAK = "Sasak";
    case TIONGHOA = "Tionghoa";
    case MAKASSAR = "Makassar";
    case CIREBON = "Cirebon";
    case LAMPUNG = "Lampung";
    case PALEMBANG = "Palembang";
    case GORONTALO = "Gorontalo";
    case MINAHASA = "Minahasa";
    case NIAS = "Nias";
    case BUTON = "Buton";
    case ATONI = "Atoni";
    case TORAJA = "Toraja";
    case KAILI = "Kaili";
    case MANGGARAI = "Manggarai";
    case OGAN = "Ogan";
    case MANDAR = "Mandar";
    case BANGKA = "Bangka";
    case BIMA = "Bima";
    case SUMBA = "Sumba";
    case MUSI = "Musi";
    case DANI = "Dani";
    case SANGIR = "Sangir";
    case REJANG = "Rejang";
    case AMBON = "Ambon";
    case TOLAKI = "Tolaki";
    case LUWU = "Luwu";
    case SUMBAWA = "Sumbawa";
    case KOMERING = "Komering";
    case GAYO = "Gayo";
    case MUNA = "Muna";
    case MEE = "Mee";
    case MONGONDOW = "Mongondow";
    case KERINCI = "Kerinci";
    case LAMAHOLOT = "Lamaholot";
    case NGADA = "Ngada";
    case OSING = "Osing";
    case KUTAI = "Kutai";
    case TIMOR_LESTE = "Timor Leste";
    case FLORES = "Flores";
    case BAJAU = "Bajau";
    case ROTE = "Rote";
    case DURI = "Duri";
    case KEI = "Kei";
    case BIAK = "Biak";
    case BELITUNG = "Belitung";
    case ALOR = "Alor";
    case SERAM = "Seram";
    case RAWAS = "Rawas";
    case LIO = "Lio";
    case PAMONA = "Pamona";
    case SAWU = "Sawu";
    case BANGGAI = "Banggai";
    case ENIM = "Enim";
    case LEMBAK = "Lembak";
    case RAMBANG = "Rambang";
    case NGALIK = "Ngalik";
    case MAMASA = "Mamasa";
    case TERNATE = "Ternate";
    case ASMAT = "Asmat";
    case SELAYAR = "Selayar";
    case MBOJO = "Mbojo";
    case DAYA = "Daya";
    case BUOL = "Buol";
    case ARAB = "Arab";
    case TOBELO = "Tobelo";
    case TANIMBAR = "Tanimbar";
    case MAMUJU = "Mamuju";
    case GALELA = "Galela";
    case YAPEN = "Yapen";
    case DAUWA = "Dauwa";
    case ALAS = "Alas";
    case SALUAN = "Saluan";
    case TALAUD = "Talaud";
    case POSO_PESISIR = "Poso Pesisir";
    case TOMINI = "Tomini";
    case MAKIAN = "Makian";
    case SAPARUA = "Saparua";
    case TIDORE = "Tidore";
    case SULA = "Sula";
    case BAWEAN = "Bawean";
    case ARFAK = "Arfak";
    case PASIR = "Pasir";
    case LAUJE = "Lauje";
    case MENTAWAI = "Mentawai";
    case SIMEULUE = "Simeulue";
    case ANEUK_JAMEE = "Aneuk Jamee";
    case MONI = "Moni";
    case DOMPU = "Dompu";
    case BURU = "Buru";
    case SINGKIL = "Singkil";
    case TAMIANG = "Tamiang";
    case AIFAT = "Aifat";
    case MARIRI = "Mariri";
    case TAA = "Taa";
    case MUKO_MUKO = "Muko-Muko";
    case KETENGBAN = "Ketengban";
    case TIALO = "Tialo";
    case KAUR = "Kaur";
    case MORONENE = "Moronene";
    case MARIND_ANIM = "Marind Anim";
    case PATTAE = "Pattae";
    case GESER_GOROM = "Geser-Gorom";
    case HARUKU = "Haruku";
    case ARU = "Aru";
    case SENTANI = "Sentani";
    case NGALUM = "Ngalum";
    case PEKAL = "Pekal";
    case MIMIKA = "Mimika";
    case LOLODA = "Loloda";
    case KISAR = "Kisar";
    case AKIT = "Akit";
    case BABAR = "Babar";
    case HUBULA = "Hubula";
    case WAROPEN = "Waropen";
    case MBAHAM = "Mbaham";
    case BALI_AGA = "Bali Aga";
    case TOBARU = "Tobaru";
    case BANDA = "Banda";
    case KAO = "Kao";
    case DAMAL = "Damal";
    case MOI = "Moi";
    case YAGHAY = "Yaghay";
    case PATANI = "Patani";
    case KALUMPANG = "Kalumpang";
    case WANDAMEN = "Wandamen";
    case TEHIT = "Tehit";
    case SUWAWA = "Suwawa";
    case KORE = "Kore";
    case IRARUTU = "Irarutu";
    case KOKODA = "Kokoda";
    case INANWATAN = "Inanwatan";
    case WAMESA = "Wamesa";
    case ATINGGOLA = "Atinggola";
    case LAIN_LAINNYA = "Lain-lainnya";

    public function getLabel(): ?string
    {
        return match ($this) {
            self::JAWA => 'Jawa',
            self::SUNDA => 'Sunda',
            self::MELAYU => 'Melayu',
            self::BATAK => 'Batak',
            self::MADURA => 'Madura',
            self::BETAWI => 'Betawi',
            self::MINANGKABAU => 'Minangkabau',
            self::BUGIS => 'Bugis',
            self::BANTEN => 'Banten',
            self::BANJAR => 'Banjar',
            self::BALI => 'Bali',
            self::ACEH => 'Aceh',
            self::DAYAK => 'Dayak',
            self::SASAK => 'Sasak',
            self::TIONGHOA => 'Tionghoa',
            self::MAKASSAR => 'Makassar',
            self::CIREBON => 'Cirebon',
            self::LAMPUNG => 'Lampung',
            self::PALEMBANG => 'Palembang',
            self::GORONTALO => 'Gorontalo',
            self::MINAHASA => 'Minahasa',
            self::NIAS => 'Nias',
            self::BUTON => 'Buton',
            self::ATONI => 'Atoni',
            self::TORAJA => 'Toraja',
            self::KAILI => 'Kaili',
            self::MANGGARAI => 'Manggarai',
            self::OGAN => 'Ogan',
            self::MANDAR => 'Mandar',
            self::BANGKA => 'Bangka',
            self::BIMA => 'Bima',
            self::SUMBA => 'Sumba',
            self::MUSI => 'Musi',
            self::DANI => 'Dani',
            self::SANGIR => 'Sangir',
            self::REJANG => 'Rejang',
            self::AMBON => 'Ambon',
            self::TOLAKI => 'Tolaki',
            self::LUWU => 'Luwu',
            self::SUMBAWA => 'Sumbawa',
            self::KOMERING => 'Komering',
            self::GAYO => 'Gayo',
            self::MUNA => 'Muna',
            self::MEE => 'Mee',
            self::MONGONDOW => 'Mongondow',
            self::KERINCI => 'Kerinci',
            self::LAMAHOLOT => 'Lamaholot',
            self::NGADA => 'Ngada',
            self::OSING => 'Osing',
            self::KUTAI => 'Kutai',
            self::TIMOR_LESTE => 'Timor Leste',
            self::FLORES => 'Flores',
            self::BAJAU => 'Bajau',
            self::ROTE => 'Rote',
            self::DURI => 'Duri',
            self::KEI => 'Kei',
            self::BIAK => 'Biak',
            self::BELITUNG => 'Belitung',
            self::ALOR => 'Alor',
            self::SERAM => 'Seram',
            self::RAWAS => 'Rawas',
            self::LIO => 'Lio',
            self::PAMONA => 'Pamona',
            self::SAWU => 'Sawu',
            self::BANGGAI => 'Banggai',
            self::ENIM => 'Enim',
            self::LEMBAK => 'Lembak',
            self::RAMBANG => 'Rambang',
            self::NGALIK => 'Ngalik',
            self::MAMASA => 'Mamasa',
            self::TERNATE => 'Ternate',
            self::ASMAT => 'Asmat',
            self::SELAYAR => 'Selayar',
            self::MBOJO => 'Mbojo',
            self::DAYA => 'Daya',
            self::BUOL => 'Buol',
            self::ARAB => 'Arab',
            self::TOBELO => 'Tobelo',
            self::TANIMBAR => 'Tanimbar',
            self::MAMUJU => 'Mamuju',
            self::GALELA => 'Galela',
            self::YAPEN => 'Yapen',
            self::DAUWA => 'Dauwa',
            self::ALAS => 'Alas',
            self::SALUAN => 'Saluan',
            self::TALAUD => 'Talaud',
            self::POSO_PESISIR => 'Poso Pesisir',
            self::TOMINI => 'Tomini',
            self::MAKIAN => 'Makian',
            self::SAPARUA => 'Saparua',
            self::TIDORE => 'Tidore',
            self::SULA => 'Sula',
            self::BAWEAN => 'Bawean',
            self::ARFAK => 'Arfak',
            self::PASIR => 'Pasir',
            self::LAUJE => 'Lauje',
            self::MENTAWAI => 'Mentawai',
            self::SIMEULUE => 'Simeulue',
            self::ANEUK_JAMEE => 'Aneuk Jamee',
            self::MONI => 'Moni',
            self::DOMPU => 'Dompu',
            self::BURU => 'Buru',
            self::SINGKIL => 'Singkil',
            self::TAMIANG => 'Tamiang',
            self::AIFAT => 'Aifat',
            self::MARIRI => 'Mariri',
            self::TAA => 'Taa',
            self::MUKO_MUKO => 'Muko-Muko',
            self::KETENGBAN => 'Ketengban',
            self::TIALO => 'Tialo',
            self::KAUR => 'Kaur',
            self::MORONENE => 'Moronene',
            self::MARIND_ANIM => 'Marind Anim',
            self::PATTAE => 'Pattae',
            self::GESER_GOROM => 'Geser-Gorom',
            self::HARUKU => 'Haruku',
            self::ARU => 'Aru',
            self::SENTANI => 'Sentani',
            self::NGALUM => 'Ngalum',
            self::PEKAL => 'Pekal',
            self::MIMIKA => 'Mimika',
            self::LOLODA => 'Loloda',
            self::KISAR => 'Kisar',
            self::AKIT => 'Akit',
            self::BABAR => 'Babar',
            self::HUBULA => 'Hubula',
            self::WAROPEN => 'Waropen',
            self::MBAHAM => 'Mbaham',
            self::BALI_AGA => 'Bali Aga',
            self::TOBARU => 'Tobaru',
            self::BANDA => 'Banda',
            self::KAO => 'Kao',
            self::DAMAL => 'Damal',
            self::MOI => 'Moi',
            self::YAGHAY => 'Yaghay',
            self::PATANI => 'Patani',
            self::KALUMPANG => 'Kalumpang',
            self::WANDAMEN => 'Wandamen',
            self::TEHIT => 'Tehit',
            self::SUWAWA => 'Suwawa',
            self::KORE => 'Kore',
            self::IRARUTU => 'Irarutu',
            self::KOKODA => 'Kokoda',
            self::INANWATAN => 'Inanwatan',
            self::WAMESA => 'Wamesa',
            self::ATINGGOLA => 'Atinggola',
            self::LAIN_LAINNYA => 'Lain-lainnya',
        };
    }
}